In [210]:
import pandas as pd
import json
import re
import ast
import numpy as np
from global_land_mask import globe

In [211]:
df = pd.read_csv("result.csv")
len(df)

99999

In [212]:
df.head()

area_id  area_contained area_type  \
0        0        0.000190     water   
1        1        0.000161     water   
2        2        0.000155     water   
3        3        0.000056      land   
4        4        0.000011     water   

                              latitude_and_longitude  
0  ['[32.319172, 163.217575]', '[32.324315, 162.1...  
1  ['[-35.735589, 107.347378]', '[-35.883432, 107...  
2  ['[1.654388, 82.484031]', '[1.900916, 82.62435...  
3  ['[-18.319043, -41.160728]', '[-18.589356, -41...  
4  ['[-57.109146, 67.107051]', '[-56.676897, 66.9...

In [14]:
data = json.load(open("vernoi.json", "r"))
data
for x in data[:20]:
    print(x)
    print("\n")

{'area_id': '0', 'area_contained': '0.0009400587531802935', 'area_type': 'water', 'latitude_and_longitude': "['[-35.655593, 164.172878]', '[-35.532144, 162.477879]', '[-34.98589, 161.817511]', '[-33.804805, 161.705416]', '[-33.999765, 163.693069]', '[-34.796751, 164.384598]', '[-34.806489, 164.38747]']"}


{'area_id': '1', 'area_contained': '0.00039960422060289643', 'area_type': 'water', 'latitude_and_longitude': "['[-28.502282, 108.516455]', '[-29.265667, 107.416561]', '[-30.627149, 107.101579]', '[-30.49761, 107.54311]', '[-29.007391, 108.770055]']"}


{'area_id': '2', 'area_contained': '0.000510347985510165', 'area_type': 'water', 'latitude_and_longitude': "['[-22.668347, 82.528614]', '[-21.455217, 82.637131]', '[-21.34583, 82.810961]', '[-21.334594, 82.942691]', '[-21.472649, 83.448832]', '[-21.791027, 83.909595]', '[-22.958193, 83.668068]', '[-23.134843, 83.424915]']"}


{'area_id': '3', 'area_contained': '0.0010969922111977856', 'area_type': 'water', 'latitude_and_longitude': "['

In [15]:
dt = {"area_id":[],
          "area_contained": [],
          "area_type":[],
          "latitude_and_longitude": []}

In [16]:
import pandas as pd
df= pd.DataFrame(columns = ['area_id','area_contained', 'area_type', 'latitude_and_longitude'])

In [17]:
df.loc[1] = ['Amy', 89, 93, 88] 


In [18]:
df

area_id area_contained area_type latitude_and_longitude
1     Amy             89        93                     88

In [19]:
import pandas as pd
import numpy as np
import time
import random

end_value = 10


In [20]:
start_time = time.time()
dictionary_list = []
for i in range(0, end_value, 1):
    dictionary_data = {k: random.random() for k in range(10)}
    dictionary_list.append(dictionary_data)

df_final = pd.DataFrame.from_dict(dictionary_list)

end_time = time.time()
print('Execution time = %.6f seconds' % (end_time-start_time))


Execution time = 0.004699 seconds


In [21]:
# 55.284704 seconds

In [22]:
df_final.head()

0         1         2         3         4         5         6  \
0  0.505710  0.222307  0.767053  0.493612  0.149950  0.077366  0.504397   
1  0.723903  0.794540  0.988928  0.493750  0.164096  0.001326  0.173067   
2  0.268214  0.264399  0.078261  0.439637  0.047333  0.875096  0.991307   
3  0.242398  0.478550  0.178396  0.683723  0.602473  0.934143  0.165838   
4  0.765708  0.570620  0.509191  0.308715  0.257296  0.312601  0.173345   

          7         8         9  
0  0.666704  0.716529  0.809591  
1  0.135967  0.434029  0.673037  
2  0.491944  0.157511  0.283745  
3  0.702205  0.423115  0.799723  
4  0.621796  0.549028  0.424048

In [124]:
import numpy as np


In [171]:
arr = np.array([0,1,2,3,4])

In [176]:
# a = np.array([
#     [[2],[3],[0]],
#     [[1],[3],[0]],
#     [[1],[2],[0]],
#     [[1],[2],[3]]]
# )
a = np.array([
    [[2],[3],[0]],
    [[1],[3],[0]],
    [[1],[2],[0]],
    [[4],[2],[3]],
    [[4],[1],[3]],
    [[4],[1],[2]]]
)

In [178]:
dt = {}
count = 0
for x in a:
    res = np.where((np.array([x])==arr).any(axis=1)[0])
    for r1 in res[0]:
        if r1 not in dt:
            dt[r1] = [count]
        else:
            dt[r1].append(count)
    count+=1
print(dt)

{0: [0, 1, 2], 2: [0, 2, 3, 5], 3: [0, 1, 3, 4], 1: [1, 2, 4, 5], 4: [3, 4, 5]}


In [118]:
np.equal(arr,a)

array([[[False,  True, False, False],
        [False, False, False,  True],
        [ True, False, False, False]],

       [[False,  True, False, False],
        [False, False, False,  True],
        [ True, False, False, False]],

       [[False,  True, False, False],
        [False, False,  True, False],
        [ True, False, False, False]],

       [[False,  True, False, False],
        [False, False,  True, False],
        [False, False, False,  True]]])

In [112]:
tmp = (a==arr)
tmp

array([[[False,  True, False, False],
        [False, False, False,  True],
        [ True, False, False, False]],

       [[False,  True, False, False],
        [False, False, False,  True],
        [ True, False, False, False]],

       [[False,  True, False, False],
        [False, False,  True, False],
        [ True, False, False, False]],

       [[False,  True, False, False],
        [False, False,  True, False],
        [False, False, False,  True]]])

In [113]:
tmp.any(axis=1)

array([[ True,  True, False,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False],
       [False,  True,  True,  True]])

In [114]:
np.where(tmp.any(axis=1))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3]),
 array([0, 1, 3, 0, 1, 3, 0, 1, 2, 1, 2, 3]))

In [109]:
np.where((a==arr).any(axis=1))

(array([], dtype=int64), array([], dtype=int64))

In [92]:
np.where((a==arr).any(axis=1))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3]),
 array([0, 2, 3, 0, 1, 3, 0, 1, 2, 1, 2, 3]))

In [93]:
import pandas as pd

In [96]:
pd.read_csv("gb.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'gb.csv'

In [5]:
arr = np.array(
    [[44624, 89647, 65334],
     [45234, 57795, 45379],
     [92301, 62197,  6857]])

In [9]:
ar = np.arange(10)

In [8]:
nw = np.expand_dims(arr, -1)

In [10]:
np.where((nw==ar).axis())

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))

In [12]:
import numpy as np

In [41]:
aa = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr = [[2, 3, 0], [1, 3, 0], [1, 2, 0], [4, 2, 3], [4, 1, 3], [4, 1, 2]]

In [42]:
type((np.expand_dims(arr, -1) == aa))

numpy.ndarray

In [46]:
tmp = np.expand_dims(arr, -1)
tmp

array([[[2],
        [3],
        [0]],

       [[1],
        [3],
        [0]],

       [[1],
        [2],
        [0]],

       [[4],
        [2],
        [3]],

       [[4],
        [1],
        [3]],

       [[4],
        [1],
        [2]]])

In [60]:
(tmp == aa)

array([[[False, False,  True, False, False, False, False, False, False,
         False],
        [False, False, False,  True, False, False, False, False, False,
         False],
        [ True, False, False, False, False, False, False, False, False,
         False]],

       [[False,  True, False, False, False, False, False, False, False,
         False],
        [False, False, False,  True, False, False, False, False, False,
         False],
        [ True, False, False, False, False, False, False, False, False,
         False]],

       [[False,  True, False, False, False, False, False, False, False,
         False],
        [False, False,  True, False, False, False, False, False, False,
         False],
        [ True, False, False, False, False, False, False, False, False,
         False]],

       [[False, False, False, False,  True, False, False, False, False,
         False],
        [False, False,  True, False, False, False, False, False, False,
         False],
        [False,

In [62]:
um = (tmp == aa).any(axis=1)
um

array([[ True, False,  True,  True, False, False, False, False, False,
        False],
       [ True,  True, False,  True, False, False, False, False, False,
        False],
       [ True,  True,  True, False, False, False, False, False, False,
        False],
       [False, False,  True,  True,  True, False, False, False, False,
        False],
       [False,  True, False,  True,  True, False, False, False, False,
        False],
       [False,  True,  True, False,  True, False, False, False, False,
        False]])

In [64]:
dir(um)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [63]:
np.where(um)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5]),
 array([0, 2, 3, 0, 1, 3, 0, 1, 2, 2, 3, 4, 1, 3, 4, 1, 2, 4]))

In [29]:
np.where((np.expand_dims(arr, -1) == aa))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5]),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]),
 array([2, 3, 0, 1, 3, 0, 1, 2, 0, 4, 2, 3, 4, 1, 3, 4, 1, 2]))

In [34]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([5,4,7,8])
c = np.array([1,2,3,4])

print((a == b ).all())  #False
print((a == c ).all())   # True
print((a == b ).any())   #False
print((a == c ).any())   #True
print((a > 3 ).all())    #False

False
True
True
True
False


In [73]:
arr = np.array([[1,2,3],[4,5,6]])
a = np.array([1,2,3,4,5,6])

In [76]:
np.where((np.expand_dims(a,-1)==arr).any(axis=1))

/home/umar/.pyenv/versions/3.7.9/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


AttributeError: 'bool' object has no attribute 'any'